export const businessTypeOptions = [
  "Sắt Thép",
  "Bao bì, đóng gói",
  "Thực phẩm",
  "Điện tử",
  "Bia rượu nước giải khát",
  "Thủy điện",
  "Nhiệt điện",
  "Ô tô, xe máy",
  "Xi măng",
  "Dệt Sợi",
  "Cao su",
  "Y tế",
  "Hóa chất, phân bón",
  "Công nghiệp thủy tinh",
  "Vật liệu xây dựng, nội thất",
  "Khác",
];
